cmake: Fix issues with static builds and CMRC
Adds uhd_rc as a link target to static builds of libuhd. This fixes
build errors like this:

```
uhd/lib/cal/database.cpp:12:10: fatal error: cmrc/cmrc.hpp: No such file
or directory
 #include <cmrc/cmrc.hpp>
```

This also adds uhd_rc as to $libuhd_libs instead of just listing it
separately, and target objects from uhd_rc to $libuhd_sources.