log: Change logging colours
TRACE: Remains purple, but that's now no longer bright
ERROR: Is now bright red (was non-bold red before)
FATAL: Is now red-on-yellow