rfnoc: modtool: Fix generation of NoC shells
Without this fix, there will be missing commas in the NoC-shells signal
list.

When trying to build an image, Vivado will fail with an error similar to:

ERROR: [VRFC 10-2063] Module <noc_shell_***> not found while
 processing module instance <noc_shell_***_i>

This fixes the missing commas.