image builder: Fix error message for missing control SEP
When attempting to generate an image core file with no control SEPs
(which is illegal), the image builder would throw an exception while
trying to produce the proper error message. The exception would look
like this:

File "[...]/site-packages/uhd/rfnoc_utils/builder_config.py", \
                                     line 330, in _check_configuration
    failures += [
TypeError: can only concatenate str (not "list") to str

This fixes the error, such that a regular error messages is shown now in
case of missing control SEPs.