uhd: C API wrapper, fix commit 30f87afcba71a07
The uhd/usrp_clock/usrp_clock.h doesn't get properly installed,
which isn't a big deal if examples are built in tree, but if
someone attempts to build a C application against libuhd,
uhd.h pulls in <uhd/usrp/usrp_clock.h> and fails as follows:

fatal error: uhd/usrp_clock/usrp_clock.h: No such file or directory

Signed-off-by: Moritz Fischer <moritz.fischer@ettus.com>